#!/usr/bin/env bash

set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)

# shellcheck disable=SC2016
"$here/bash" -c '
set -euxo pipefail

_find_xsd_path() {
    find /cnxml/poet -type d -name xsd | head -n 1
}

generate-schema() {
    while test -n "${1:-}"; do
        case "$1" in
            --unpatched)
                do_patch=0
            ;;
            *)
                echo "Unknown option: $1" >&2
            ;;
        esac
        shift 1
    done

    if ! [ -e poet ]; then
        mkdir poet
        cd poet
        git init
        git remote add origin https://github.com/openstax/poet
        cd -
    fi

    cd poet
    git fetch --depth=1 origin $branch
    git checkout $branch
    git reset --hard origin/$branch
    cd -

    xsd_path=$(_find_xsd_path)

    jing -i -s ./cnxml/xml/poet/schema/rng/poet-jing.rng > poet-simplified.rng
    trang -I rng -O xsd poet-simplified.rng $xsd_path/mathml.xsd

    cd ./poet
    rm -f $xsd_path*.rej
    rm -f $xsd_path*.orig
    if [ ${do_patch:-1} -eq 1 ]; then
        patch -p1 < $xsd_path/trang.patch
    else
        git add $xsd_path
        git commit -m "unpatched"
        git checkout origin/$branch -- $xsd_path
        git restore --staged .
        echo "Ready for changes. When you are done, run generate-patch." >&2
    fi
}

generate-patch() {
    cd poet
    xsd_path=$(_find_xsd_path)
    git restore --staged . || true
    git diff --patch -- $xsd_path/*.xsd > $xsd_path/trang.patch
}

command="${1:?Command is required}"
shift

args=()
while test -n "${1:-}"; do
    case "$1" in
        --branch)
            branch="$2"
            shift
        ;;
        *)
            args+=("$1")
        ;;
    esac
    shift
done
: ${branch:=main}

case "$command" in
    "generate-schema")
        generate-schema "${args[@]}"
    ;;
    "generate-patch")
        generate-patch "${args[@]}"
    ;;
    *)
        echo "Unknown command" >&2
    ;;
esac

' bash "$@"

echo "Done! See updated files in: $(cd ./poet/client/static/xsd && pwd)" >&2
